
on:
  workflow_call:

env:
  BUILD_TYPE: Release

jobs:

  CppCheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install cppCheck
      run: sudo apt install -y cppcheck

    - name: Configure CMake
      run: cmake -B "${{github.workspace}}/build" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: CppCheck
      run:
        cppcheck --version
        && cmake --build ${{github.workspace}}/build --target hub-cppCheck
   

  Doxygen:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ssciwr/doxygen-install@v1.3.0

    - name: Configure CMake
      run: cmake -B "${{github.workspace}}/build" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DHUB_BUILD_DOC=ON

    - name: Doxygen
      run:
        doxygen --version &&
        cmake --build ${{github.workspace}}/build --target hub-doc-doxygen


  Format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install clang-format
      run: 
        sudo apt install -y clang-format
        
    - name: Install cmake-format
      run: 
        sudo apt install -y cmake-format
        
    - name: Configure CMake
      run: cmake -B "${{github.workspace}}/build" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Check code format
      run: clang-format --version && echo "cmake-format version $(cmake-format --version)"
        && cmake --build ${{github.workspace}}/build --target hub-format
        && git diff --exit-code

