
name: CI

defaults:
  run:
    shell: bash

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:

  CodeQuality:
    uses: ./.github/workflows/codeQuality.yml

  Ubuntu_gcc:
    needs: CodeQuality
    uses: ./.github/workflows/buildAndTest.yml
    with:
      name: Ubuntu_gcc
      os: ubuntu-latest
      cc: gcc
      cxx: g++
      build-type: Release
      coverage: ON

  Windows_MSVC:
    needs: CodeQuality
    uses: ./.github/workflows/buildAndTest.yml
    with:
      name: Windows_MSVC
      os: windows-latest
      cc: cl
      cxx: cl
      build-type: Release
      coverage: OFF # always off because lcov to install

  MacOS_clang:
    needs: CodeQuality
    uses: ./.github/workflows/buildAndTest.yml
    with:
      name: MacOS_clang
      os: macos-latest
      cc: clang
      cxx: clang++
      build-type: Release
      coverage: OFF

  Doc:
    if: github.event_name == 'push'
    needs: [ Ubuntu_gcc, Windows_MSVC, MacOS_clang ]
    uses: ./.github/workflows/deployDoc.yml

  External:
    if: github.event_name == 'push'
    needs: Doc
    uses: ./.github/workflows/testAsExternalProject.yml

  Submodule:
    if: github.event_name == 'push'
    needs: Doc
    uses: ./.github/workflows/testAsSubmodule.yml

  FetchContent:
    if: github.event_name == 'push'
    needs: Doc
    uses: ./.github/workflows/testAsFetchContent.yml


